"""
Student Pydantic models.

registration_no is auto-generated by the DB (migration 038) and is read-only.
Per-year class/section/roll live in student_enrollments; the legacy class_id /
section_id columns on the student row are the current-year mirror.
"""
from typing import Optional, Literal
from pydantic import BaseModel, Field

Gender = Literal["male", "female", "other"]


class StudentCreate(BaseModel):
    name: str
    class_field: Optional[str] = Field(default=None, alias="class")
    class_id: Optional[int] = None
    section_id: Optional[int] = None
    academic_year_id: Optional[int] = None
    # Identity / bio (registration_no is auto-assigned by the DB).
    admission_date: Optional[str] = None
    date_of_birth: Optional[str] = None
    gender: Optional[Gender] = None
    address: Optional[str] = None
    guardian_id: Optional[int] = None

    model_config = {"populate_by_name": True}


class StudentUpdate(BaseModel):
    name: Optional[str] = None
    class_field: Optional[str] = Field(default=None, alias="class")
    class_id: Optional[int] = None
    section_id: Optional[int] = None
    academic_year_id: Optional[int] = None
    admission_date: Optional[str] = None
    date_of_birth: Optional[str] = None
    gender: Optional[Gender] = None
    address: Optional[str] = None
    guardian_id: Optional[int] = None

    model_config = {"populate_by_name": True}


class StudentResponse(BaseModel):
    id: int
    name: str
    registration_no: Optional[str] = None
    class_field: Optional[str] = Field(default=None, alias="class")
    class_id: Optional[int] = None
    section_id: Optional[int] = None
    section: Optional[str] = None              # section name (enriched)
    academic_year_id: Optional[int] = None
    admission_date: Optional[str] = None
    date_of_birth: Optional[str] = None
    gender: Optional[str] = None
    address: Optional[str] = None
    guardian_id: Optional[int] = None
    is_deleted: Optional[bool] = False
    created_at: Optional[str] = None

    model_config = {"populate_by_name": True}
